const gamesObj = [
    {
        id: 1,
        team1Abbreviation: 'MIN',
        team1: 'Minnesota Vikings',
        team1Location: 'Away',
        team2Abbreviation: 'NO',
        team2: 'New Orleans Saints',
        team2Location: 'Home',
        spread: -7.5,
        location: 'Mercedes-Benz Superdome',
        date: 'December 25, 2020',
    },
    {
        id: 2,
        team1Abbreviation: 'TB',
        team1: 'Tampa Bay Buccaneers',
        team1Location: 'Away',
        team2Abbreviation: 'DET',
        team2: 'Detroit Lions',
        team2Location: 'Home',
        spread: -9.5,
        location: 'Ford Field',
        date: 'December 26, 2020',
    },
    {
        id: 3,
        team1Abbreviation: 'SF',
        team1: 'San Francisco 49ers',
        team1Location: 'Away',
        team2Abbreviation: 'ARI',
        team2: 'Arizona Cardinals',
        team2Location: 'Home',
        spread: -5.5,
        location: 'State Farm Stadium',
        date: 'December 26, 2020',
    },
    {
        id: 4,
        team1Abbreviation: 'MIA',
        team1: 'Miami Dolphins',
        team1Location: 'Away',
        team2Abbreviation: 'LV',
        team2: 'Las Vegas Raiders',
        team2Location: 'Home',
        spread: -3.5,
        location: 'Allegiant Stadium',
        date: 'December 26, 2020',
    },
    {
        id: 5,
        team1Abbreviation: 'ATL',
        team1: 'Atlanta Falcons',
        team1Location: 'Away',
        team2Abbreviation: 'KC',
        team2: 'Kansas City Chiefs',
        team2Location: 'Home',
        spread: -10.5,
        location: 'Arrowhead Stadium',
        date: 'December 27, 2020',
    },
    {
        id: 6,
        team1Abbreviation: 'CLE',
        team1: 'Cleveland Browns',
        team1Location: 'Away',
        team2Abbreviation: 'NYJ',
        team2: 'New York Jets',
        team2Location: 'Home',
        spread: -7.5,
        location: 'MetLife Stadium',
        date: 'December 27, 2020',
    },
    {
        id: 7,
        team1Abbreviation: 'IND',
        team1: 'Indianapolis Colts',
        team1Location: 'Away',
        team2Abbreviation: 'PIT',
        team2: 'Pittsburgh Steelers',
        team2Location: 'Home',
        spread: -6.5,
        location: 'Heinz Field',
        date: 'December 27, 2020',
    },
    {
        id: 8,
        team1Abbreviation: 'CHI',
        team1: 'Chicago Bears',
        team1Location: 'Away',
        team2Abbreviation: 'JAX',
        team2: 'Jacksonville Jaguars',
        team2Location: 'Home',
        spread: -7.5,
        location: 'TIAA Bank Field',
        date: 'December 27, 2020',
    },
    {
        id: 9,
        team1Abbreviation: 'CIN',
        team1: 'Cincinnati Bengals',
        team1Location: 'Away',
        team2Abbreviation: 'HOU',
        team2: 'Houston Texans',
        team2Location: 'Home',
        spread: -9.5,
        location: 'NRG Stadium',
        date: 'December 27, 2020',
    },
    {
        id: 10,
        team1Abbreviation: 'NYG',
        team1: 'New York Giants',
        team1Location: 'Away',
        team2Abbreviation: 'BAL',
        team2: 'Baltimore Ravens',
        team2Location: 'Home',
        spread: -13.5,
        location: 'M&T Bank Stadium',
        date: 'December 27, 2020',
    },
    {
        id: 11,
        team1Abbreviation: 'CAR',
        team1: 'Carolina Panthers',
        team1Location: 'Away',
        team2Abbreviation: 'WAS',
        team2: 'Washington Football Team',
        team2Location: 'Home',
        spread: -4.5,
        location: 'FedExField',
        date: 'December 27, 2020',
    },
    {
        id: 12,
        team1Abbreviation: 'DEN',
        team1: 'Denver Broncos',
        team1Location: 'Away',
        team2Abbreviation: 'LAC',
        team2: 'Los Angeles Chargers',
        team2Location: 'Home',
        spread: -3.5,
        location: 'SoFi Stadium',
        date: 'December 27, 2020',
    },
    {
        id: 13,
        team1Abbreviation: 'PHI',
        team1: 'Philadelphia Eagles',
        team1Location: 'Away',
        team2Abbreviation: 'DAL',
        team2: 'Dallas Cowboys',
        team2Location: 'Home',
        spread: -2.5,
        location: 'AT&T Stadium',
        date: 'December 27, 2020',
    },
    {
        id: 14,
        team1Abbreviation: 'LAR',
        team1: 'Los Angeles Rams',
        team1Location: 'Away',
        team2Abbreviation: 'SEA',
        team2: 'Seattle Seahawks',
        team2Location: 'Home',
        spread: -6.5,
        location: 'Lumen Field',
        date: 'December 27, 2020',
    },
    {
        id: 15,
        team1Abbreviation: 'TEN',
        team1: 'Tennessee Titans',
        team1Location: 'Away',
        team2Abbreviation: 'GB',
        team2: 'Green Bay Packers',
        team2Location: 'Home',
        spread: -3.5,
        location: 'Lambeau Field',
        date: 'December 27, 2020',
    },
    {
        id: 16,
        team1Abbreviation: 'BUF',
        team1: 'Buffalo Bills',
        team1Location: 'Away',
        team2Abbreviation: 'NE',
        team2: 'New England Patriots',
        team2Location: 'Home',
        spread: -6.5,
        location: 'Gillette Stadium',
        date: 'December 28, 2020',
    },
];

export default gamesObj;
